# Generated by Django 2.2.16 on 2022-09-27 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Galeria_Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(verbose_name='Contenido de la Imagen')),
                ('orden', models.IntegerField(default=1, verbose_name='Orden de la Imagen')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='empresa/galeria', verbose_name='Imagen_Galeria')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado de la Imagen')),
            ],
            options={
                'verbose_name_plural': 'Galería de la Empresa',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Informacion_Empleo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idcargo', models.IntegerField()),
                ('descripcion', models.TextField(max_length=300)),
                ('num_vacantes', models.IntegerField()),
                ('ciudad', models.CharField(max_length=50)),
                ('orden', models.IntegerField(default=1, verbose_name='Orden de Empleo')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='informacion_empleo', verbose_name='Imagen_Info_Empleo')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado de la Imagen')),
            ],
            options={
                'verbose_name_plural': 'Información de Empleo',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Productos_Servicios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del producto o servicio')),
                ('descripcion', models.TextField(max_length=350)),
                ('imagen', models.ImageField(upload_to='Sectores', verbose_name='Imagen_Sectores')),
                ('estado', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True)),
                ('es_producto', models.BooleanField(choices=[(True, 'Producto'), (False, 'Servicio')], default=True, verbose_name='Es un producto')),
            ],
            options={
                'verbose_name_plural': 'Productos y Servicios Financieros',
            },
        ),
        migrations.CreateModel(
            name='Redes_Sociales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='empresa/redes_sociales', verbose_name='Imagen')),
                ('link', models.CharField(max_length=100)),
                ('orden', models.IntegerField(default=1, verbose_name='Orden de las redes sociales')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado de la Red Social')),
                ('empresa', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Redes Sociales de la Empresa',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Responsabilidad_Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.TextField(max_length=400, verbose_name='Descripción')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado de la Imagen')),
                ('imagen', models.ImageField(upload_to='empresa/Responsabilidad_Social', verbose_name='Imagen_Responsabilidad_Social')),
                ('fecha_realizacion', models.DateField()),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name_plural': 'Responsabilidad Social',
                'ordering': ['fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Sala_Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('link', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado de la Imagen')),
                ('imagen', models.ImageField(upload_to='sala_videos', verbose_name='Imagen_Sala_Videos')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name_plural': 'Sala de Videos',
                'ordering': ['fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Valores_Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('empresa', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Valores de la Empresa',
            },
        ),
        migrations.CreateModel(
            name='Detalle_Productos_Servicios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisitos', models.TextField()),
                ('frecuencia_pago', models.IntegerField()),
                ('producto_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='getDetalleProductosServicios', to='ws_administracion.Productos_Servicios')),
            ],
            options={
                'verbose_name_plural': 'Detalle de los productos y servicios',
                'unique_together': {('producto_servicio', 'frecuencia_pago')},
            },
        ),
    ]
