# Generated by Django 4.1.4 on 2025-08-18 19:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('mensaje', models.TextField()),
                ('respondido', models.BooleanField(default=False)),
                ('fecha_envio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Galeria_Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(verbose_name='Contenido de la Imagen')),
                ('orden', models.IntegerField(default=1, verbose_name='Orden de la Imagen')),
                ('imagen', models.ImageField(blank=True, max_length=250, null=True, upload_to='finsurhn_ws/galeria', verbose_name='Imagen_Galeria')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado de la Imagen')),
            ],
            options={
                'verbose_name_plural': 'Galería de la Empresa',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Informacion_Empleo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idcargo', models.IntegerField()),
                ('descripcion', models.TextField(max_length=300)),
                ('num_vacantes', models.IntegerField()),
                ('ciudad', models.CharField(max_length=50)),
                ('orden', models.IntegerField(default=1, verbose_name='Orden de Empleo')),
                ('imagen', models.ImageField(blank=True, max_length=250, null=True, upload_to='finsurhn_ws/informacion_empleo')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado de la Imagen')),
            ],
            options={
                'verbose_name_plural': 'Información de Empleo',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Productos_Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del producto o servicio')),
                ('descripcion', models.TextField(max_length=350)),
                ('imagen', models.ImageField(max_length=250, upload_to='finsurhn_ws/productos_servicios')),
                ('estado', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True)),
                ('es_producto', models.BooleanField(choices=[(True, 'Producto'), (False, 'Servicio')], default=True, verbose_name='Es un producto')),
            ],
            options={
                'verbose_name_plural': 'Productos y Servicios Financieros',
            },
        ),
        migrations.CreateModel(
            name='Redes_Sociales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('imagen', models.ImageField(blank=True, max_length=250, null=True, upload_to='finsurhn_ws/redes_sociales', verbose_name='Imagen')),
                ('link', models.CharField(max_length=100)),
                ('orden', models.IntegerField(default=1, verbose_name='Orden de las redes sociales')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado de la Red Social')),
            ],
            options={
                'verbose_name_plural': 'Redes Sociales de la Empresa',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Responsabilidad_Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.TextField(max_length=400, verbose_name='Descripción')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado de la Imagen')),
                ('imagen', models.ImageField(max_length=250, upload_to='finsurhn_ws/responsabilidad_social')),
                ('fecha_realizacion', models.DateField()),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name_plural': 'Responsabilidad Social',
                'ordering': ['fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Sala_Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('link', models.TextField()),
                ('estado', models.BooleanField(default=True, verbose_name='Estado de la Imagen')),
                ('imagen', models.ImageField(max_length=250, upload_to='finsurhn_ws/sala_videos')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name_plural': 'Sala de Videos',
                'ordering': ['fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Valores_Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Valores de la Empresa',
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(max_length=20, unique=True)),
                ('primerNombre', models.CharField(max_length=50)),
                ('segundoNombre', models.CharField(blank=True, max_length=50, null=True)),
                ('primerApellido', models.CharField(max_length=50)),
                ('segundoApellido', models.CharField(blank=True, max_length=50, null=True)),
                ('celular', models.CharField(max_length=20)),
                ('direccion', models.TextField()),
                ('montoSolicitado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descripcionTipoIngreso', models.TextField()),
                ('estado', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ws_administracion.estadosolicitud')),
                ('formaPago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ws_administracion.formapago')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ws_administracion.sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_Productos_Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisitos', models.TextField()),
                ('frecuencia_pago', models.IntegerField()),
                ('producto_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='getDetalleProductosServicios', to='ws_administracion.productos_servicios')),
            ],
            options={
                'verbose_name_plural': 'Detalle de los productos y servicios',
                'unique_together': {('producto_servicio', 'frecuencia_pago')},
            },
        ),
    ]
