# Generated by Django 4.1.4 on 2023-02-13 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ws_administracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_productos_servicios',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='galeria_empresa',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='galeria_empresa',
            name='imagen',
            field=models.ImageField(blank=True, max_length=250, null=True, upload_to='finsurhn_ws/galeria', verbose_name='Imagen_Galeria'),
        ),
        migrations.AlterField(
            model_name='informacion_empleo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='informacion_empleo',
            name='imagen',
            field=models.ImageField(blank=True, max_length=250, null=True, upload_to='finsurhn_ws/informacion_empleo'),
        ),
        migrations.AlterField(
            model_name='productos_servicios',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productos_servicios',
            name='imagen',
            field=models.ImageField(max_length=250, upload_to='finsurhn_ws/productos_servicios'),
        ),
        migrations.AlterField(
            model_name='redes_sociales',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='redes_sociales',
            name='imagen',
            field=models.ImageField(blank=True, max_length=250, null=True, upload_to='finsurhn_ws/redes_sociales', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='responsabilidad_social',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='responsabilidad_social',
            name='imagen',
            field=models.ImageField(max_length=250, upload_to='finsurhn_ws/responsabilidad_social'),
        ),
        migrations.AlterField(
            model_name='sala_videos',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sala_videos',
            name='imagen',
            field=models.ImageField(max_length=250, upload_to='finsurhn_ws/sala_videos'),
        ),
        migrations.AlterField(
            model_name='valores_empresa',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
