# Generated by Django 4.1.4 on 2025-08-18 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ws_administracion', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Solicitud',
        ),
    ]
