# Generated by Django 4.1.4 on 2025-08-18 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ws_administracion', '0002_delete_solicitud'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(max_length=20, unique=True)),
                ('primerNombre', models.CharField(max_length=50)),
                ('segundoNombre', models.CharField(blank=True, max_length=50, null=True)),
                ('primerApellido', models.CharField(max_length=50)),
                ('segundoApellido', models.CharField(blank=True, max_length=50, null=True)),
                ('celular', models.CharField(max_length=20)),
                ('direccion', models.TextField()),
                ('montoSolicitado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descripcionTipoIngreso', models.TextField()),
                ('estado', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ws_administracion.estadosolicitud')),
                ('formaPago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ws_administracion.formapago')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ws_administracion.sucursal')),
            ],
        ),
    ]
