# Generated by Django 4.1.4 on 2023-02-18 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ws_administracion', '0003_alter_sala_videos_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redes_sociales',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='valores_empresa',
            name='empresa',
        ),
    ]
