# Generated by Django 4.1.4 on 2025-08-18 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ws_administracion', '0003_solicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
