# Generated by Django 4.1.4 on 2025-08-19 00:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ws_administracion', '0004_solicitud_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='fecha_envio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
